server:
  port: 1111
spring:
  application:
    name: HI-SERVICE

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-39806476.okta.com/oauth2/default
      client:
        registration:
          my-internal-client:
            provider: okta
            authorizationGrantType: client_credentials
            scope: internal
            clientId: 0oaaejbnvl6HKB9aW5d7
            clientSecret: 7ZxQE8P0Wk-vhizLqfEwsNACAeaZFh3AsxAYV44E


        provider:
          okta:
            issuerUri: https://dev-39806476.okta.com/oauth2/default
eureka:
  client:
    service-url:
      default-zone: ${DISCOVERY_URL:http://localhost:8761}/eureka/



okta:
  oauth2:
    issuer: https://dev-39806476.okta.com/oauth2/default
    audience: api://default